apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auto-docker-deployer-app
  name: auto-docker-deployer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-docker-deployer-app
  template:
    metadata:
      labels:
        app: auto-docker-deployer-app
    spec:
      containers:
        - image: autodockerdeployer
          name: auto-docker-deployer-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-docker-deployer-app
  name: auto-docker-deployer-app
spec:
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8095
  selector:
    app: auto-docker-deployer-app
  type: NodePort