apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "registry.hub.docker.com": {
                "auth": "Y2hhbmRyYW1nYzoxYmU0MGU0OC03ZmY5LTRkMDMtOTk2Mi01OGNiNzA5NTdkYTgK"
            }
        }
    }
type: kubernetes.io/dockerconfigjson